<?xml version="1.0" encoding="utf-8"?><Database Name="Pyxis" Class="PyxisDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CH\SQLEXPRESS;Initial Catalog=Pyxis;Integrated Security=True" SettingsObjectName="DataBase.Properties.Settings" SettingsPropertyName="PyxisConnectionString4" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Calificaciones" Member="Calificaciones">
    <Type Name="Calificaciones">
      <Column Name="Idcalificacion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="opinion" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="puntuacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_ca" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="servicioId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Servicios_Calificaciones" Member="Servicios" ThisKey="servicioId" OtherKey="Idservicio" Type="Servicios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Localidades" Member="Localidades">
    <Type Name="Localidades">
      <Column Name="idLocalidad" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Localidades_Usuarios" Member="Usuarios" ThisKey="idLocalidad" OtherKey="localidad" Type="Usuarios" />
    </Type>
  </Table>
  <Table Name="dbo.Mascotas" Member="Mascotas">
    <Type Name="Mascotas">
      <Column Name="Idmascota" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tamaño" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="edad" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="raza" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nombre_ma" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Idusuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Razas_Mascotas" Member="Razas" ThisKey="raza" OtherKey="idRaza" Type="Razas" IsForeignKey="true" />
      <Association Name="Usuarios_Mascotas" Member="Usuarios" ThisKey="Idusuario" OtherKey="Idusuario" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Paseadores" Member="Paseadores">
    <Type Name="Paseadores">
      <Column Name="Idpaseador" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="calificacion_prom" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="especialidad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pa_idusu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="precio" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Horainicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoraFin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dias" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Experiencia" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Paseadores_PQR" Member="PQR" ThisKey="Idpaseador" OtherKey="idpas" Type="PQR" />
      <Association Name="Paseadores_Servicios" Member="Servicios" ThisKey="Idpaseador" OtherKey="pa_serv" Type="Servicios" />
      <Association Name="Usuarios_Paseadores" Member="Usuarios" ThisKey="pa_idusu" OtherKey="Idusuario" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PQR" Member="PQR">
    <Type Name="PQR">
      <Column Name="IdPQR" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fecha_PQR" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="comentario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="idusu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idpas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Paseadores_PQR" Member="Paseadores" ThisKey="idpas" OtherKey="Idpaseador" Type="Paseadores" IsForeignKey="true" />
      <Association Name="Usuarios_PQR" Member="Usuarios" ThisKey="idusu" OtherKey="Idusuario" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Razas" Member="Razas">
    <Type Name="Razas">
      <Column Name="idRaza" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Razas_Mascotas" Member="Mascotas" ThisKey="idRaza" OtherKey="raza" Type="Mascotas" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Roles">
      <Column Name="idrol" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Roles_Usuarios" Member="Usuarios" ThisKey="idrol" OtherKey="Usu_rol" Type="Usuarios" />
    </Type>
  </Table>
  <Table Name="dbo.Servicios" Member="Servicios">
    <Type Name="Servicios">
      <Column Name="Idservicio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fecha_se" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="estado_se" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="detalles_se" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="se_idusuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pa_serv" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Servicios_Calificaciones" Member="Calificaciones" ThisKey="Idservicio" OtherKey="servicioId" Type="Calificaciones" />
      <Association Name="Paseadores_Servicios" Member="Paseadores" ThisKey="pa_serv" OtherKey="Idpaseador" Type="Paseadores" IsForeignKey="true" />
      <Association Name="Usuarios_Servicios" Member="Usuarios" ThisKey="se_idusuario" OtherKey="Idusuario" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="Idusuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="documento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tipo_doc" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="localidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="telefono" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="contrasena" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Usu_rol" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImgPerfil" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Usuarios_Mascotas" Member="Mascotas" ThisKey="Idusuario" OtherKey="Idusuario" Type="Mascotas" />
      <Association Name="Usuarios_Paseadores" Member="Paseadores" ThisKey="Idusuario" OtherKey="pa_idusu" Type="Paseadores" />
      <Association Name="Usuarios_PQR" Member="PQR" ThisKey="Idusuario" OtherKey="idusu" Type="PQR" />
      <Association Name="Usuarios_Servicios" Member="Servicios" ThisKey="Idusuario" OtherKey="se_idusuario" Type="Servicios" />
      <Association Name="Roles_Usuarios" Member="Roles" ThisKey="Usu_rol" OtherKey="idrol" Type="Roles" IsForeignKey="true" />
      <Association Name="Localidades_Usuarios" Member="Localidades" ThisKey="localidad" OtherKey="idLocalidad" Type="Localidades" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.ActualizarUsuario" Method="ActualizarUsuario">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="APELLIDO" Parameter="aPELLIDO" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TELEFONO" Parameter="tELEFONO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="localidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="CORREO" Parameter="cORREO" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.buscar" Method="buscar">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="buscarResult">
      <Column Name="Idusuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.buscarpaseadorN" Method="buscarpaseadorN">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="buscarpaseadorNResult">
      <Column Name="Idpaseador" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="correo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="localidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="precio" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BusquedaServicio" Method="BusquedaServicio">
    <Parameter Name="HoraIni" Parameter="horaIni" Type="System.Int32" DbType="Int" />
    <Parameter Name="Localidad" Parameter="localidad" Type="System.Int32" DbType="Int" />
    <ElementType Name="BusquedaServicioResult">
      <Column Name="Idpaseador" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="calificacion_prom" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="especialidad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pa_idusu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="precio" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Horainicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoraFin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dias" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Experiencia" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" />
      <Column Name="Idusuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="documento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tipo_doc" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="localidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="telefono" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="contrasena" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Usu_rol" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImgPerfil" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Consultarpaseador" Method="Consultarpaseador">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="ConsultarpaseadorResult">
      <Column Name="Idpaseador" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="correo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="localidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tipo_doc" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="documento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Experiencia" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Crearpaseador" Method="Crearpaseador">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Experiencia" Parameter="experiencia" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" />
    <Parameter Name="Especialidad" Parameter="especialidad" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="precio" Type="System.Double" DbType="Float" />
    <Parameter Name="HoraIni" Parameter="horaIni" Type="System.Int32" DbType="Int" />
    <Parameter Name="HoraFin" Parameter="horaFin" Type="System.Int32" DbType="Int" />
    <Parameter Name="Dias" Parameter="dias" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CrearMascotas" Method="CrearMascotas">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="tamaño" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Edad" Parameter="edad" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="raza" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CrearUsuario" Method="CrearUsuario">
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="APELLIDO" Parameter="aPELLIDO" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CONTRASENA" Parameter="cONTRASENA" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CORREO" Parameter="cORREO" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="telefono" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="localidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="documento" Type="System.Int32" DbType="Int" />
    <Parameter Name="tipodoc" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="img" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CrearServicio" Method="CrearServicio">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="fecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="estado_se" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="detalles" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="idpa" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Inactivarpaseador" Method="Inactivarpaseador">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="accion" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.mostrarimagen" Method="mostrarimagen">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="mostrarimagenResult">
      <Column Name="ImgPerfil" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.OrganizarPaseador" Method="OrganizarPaseador">
    <ElementType Name="OrganizarPaseadorResult">
      <Column Name="Idpaseador" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Usunombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="correo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="precio" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Experiencia" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Organizarusuario" Method="Organizarusuario">
    <ElementType Name="OrganizarusuarioResult">
      <Column Name="Idusuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="usunom" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="correo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.RolSeleccionador" Method="RolSeleccionador">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="numero_rol" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.MostrarDatosPerfil" Method="MostrarDatosPerfil">
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="MostrarDatosPerfilResult">
      <Column Name="Idusuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="documento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tipo_doc" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="localidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="telefono" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="contrasena" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Usu_rol" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImgPerfil" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.OrganizarServicio" Method="OrganizarServicio">
    <ElementType Name="OrganizarServicioResult">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreUsuario" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Horainicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoraFin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.PedirServicio" Method="PedirServicio">
    <Parameter Name="Localidad" Parameter="localidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="HoraBusqueda" Parameter="horaBusqueda" Type="System.Int32" DbType="Int" />
    <ElementType Name="PedirServicioResult">
      <Column Name="NombreUsuario" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Horainicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoraFin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>