#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Pyxis")]
	public partial class PyxisDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCalificaciones(Calificaciones instance);
    partial void UpdateCalificaciones(Calificaciones instance);
    partial void DeleteCalificaciones(Calificaciones instance);
    partial void InsertLocalidades(Localidades instance);
    partial void UpdateLocalidades(Localidades instance);
    partial void DeleteLocalidades(Localidades instance);
    partial void InsertMascotas(Mascotas instance);
    partial void UpdateMascotas(Mascotas instance);
    partial void DeleteMascotas(Mascotas instance);
    partial void InsertPaseadores(Paseadores instance);
    partial void UpdatePaseadores(Paseadores instance);
    partial void DeletePaseadores(Paseadores instance);
    partial void InsertPQR(PQR instance);
    partial void UpdatePQR(PQR instance);
    partial void DeletePQR(PQR instance);
    partial void InsertRazas(Razas instance);
    partial void UpdateRazas(Razas instance);
    partial void DeleteRazas(Razas instance);
    partial void InsertRoles(Roles instance);
    partial void UpdateRoles(Roles instance);
    partial void DeleteRoles(Roles instance);
    partial void InsertServicios(Servicios instance);
    partial void UpdateServicios(Servicios instance);
    partial void DeleteServicios(Servicios instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    #endregion
		
		public PyxisDataContext() : 
				base(global::DataBase.Properties.Settings.Default.PyxisConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public PyxisDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PyxisDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PyxisDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PyxisDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Calificaciones> Calificaciones
		{
			get
			{
				return this.GetTable<Calificaciones>();
			}
		}
		
		public System.Data.Linq.Table<Localidades> Localidades
		{
			get
			{
				return this.GetTable<Localidades>();
			}
		}
		
		public System.Data.Linq.Table<Mascotas> Mascotas
		{
			get
			{
				return this.GetTable<Mascotas>();
			}
		}
		
		public System.Data.Linq.Table<Paseadores> Paseadores
		{
			get
			{
				return this.GetTable<Paseadores>();
			}
		}
		
		public System.Data.Linq.Table<PQR> PQR
		{
			get
			{
				return this.GetTable<PQR>();
			}
		}
		
		public System.Data.Linq.Table<Razas> Razas
		{
			get
			{
				return this.GetTable<Razas>();
			}
		}
		
		public System.Data.Linq.Table<Roles> Roles
		{
			get
			{
				return this.GetTable<Roles>();
			}
		}
		
		public System.Data.Linq.Table<Servicios> Servicios
		{
			get
			{
				return this.GetTable<Servicios>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Organizarusuario")]
		public ISingleResult<OrganizarusuarioResult> Organizarusuario()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<OrganizarusuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarUsuario")]
		public int ActualizarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO", DbType="VarChar(50)")] string aPELLIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="BigInt")] System.Nullable<long> tELEFONO, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> localidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="VarChar(100)")] string cORREO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, nOMBRE, aPELLIDO, tELEFONO, localidad, cORREO);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.buscar")]
		public ISingleResult<buscarResult> buscar([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((ISingleResult<buscarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.buscarpaseadorN")]
		public ISingleResult<buscarpaseadorNResult> buscarpaseadorN([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((ISingleResult<buscarpaseadorNResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Consultarpaseador")]
		public ISingleResult<ConsultarpaseadorResult> Consultarpaseador([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<ConsultarpaseadorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CrearMascotas")]
		public int CrearMascotas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tamaño, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Edad", DbType="VarChar(50)")] string edad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string raza, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, tamaño, edad, raza, nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Crearpaseador")]
		public int Crearpaseador([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string disponibilidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Experiencia", DbType="VarChar(20)")] string experiencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Especialidad", DbType="VarChar(50)")] string especialidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> precio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, disponibilidad, experiencia, especialidad, precio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CrearServicio")]
		public int CrearServicio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string estado_se, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string detalles, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idpa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, fecha, estado_se, detalles, idpa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Inactivarpaseador")]
		public int Inactivarpaseador([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.OrganizarPaseador")]
		public ISingleResult<OrganizarPaseadorResult> OrganizarPaseador()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<OrganizarPaseadorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CrearUsuario")]
		public int CrearUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO", DbType="VarChar(50)")] string aPELLIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRASENA", DbType="VarChar(50)")] string cONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="VarChar(100)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> localidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> documento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string tipodoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Image")] System.Data.Linq.Binary img)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, aPELLIDO, cONTRASENA, cORREO, telefono, localidad, documento, tipodoc, img);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarimagen")]
		public ISingleResult<mostrarimagenResult> mostrarimagen([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<mostrarimagenResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Calificaciones")]
	public partial class Calificaciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Idcalificacion;
		
		private string _opinion;
		
		private int _puntuacion;
		
		private System.Nullable<System.DateTime> _fecha_ca;
		
		private System.Nullable<int> _servicioId;
		
		private EntityRef<Servicios> _Servicios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdcalificacionChanging(int value);
    partial void OnIdcalificacionChanged();
    partial void OnopinionChanging(string value);
    partial void OnopinionChanged();
    partial void OnpuntuacionChanging(int value);
    partial void OnpuntuacionChanged();
    partial void Onfecha_caChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_caChanged();
    partial void OnservicioIdChanging(System.Nullable<int> value);
    partial void OnservicioIdChanged();
    #endregion
		
		public Calificaciones()
		{
			this._Servicios = default(EntityRef<Servicios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idcalificacion", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Idcalificacion
		{
			get
			{
				return this._Idcalificacion;
			}
			set
			{
				if ((this._Idcalificacion != value))
				{
					this.OnIdcalificacionChanging(value);
					this.SendPropertyChanging();
					this._Idcalificacion = value;
					this.SendPropertyChanged("Idcalificacion");
					this.OnIdcalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opinion", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string opinion
		{
			get
			{
				return this._opinion;
			}
			set
			{
				if ((this._opinion != value))
				{
					this.OnopinionChanging(value);
					this.SendPropertyChanging();
					this._opinion = value;
					this.SendPropertyChanged("opinion");
					this.OnopinionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntuacion", DbType="Int NOT NULL")]
		public int puntuacion
		{
			get
			{
				return this._puntuacion;
			}
			set
			{
				if ((this._puntuacion != value))
				{
					this.OnpuntuacionChanging(value);
					this.SendPropertyChanging();
					this._puntuacion = value;
					this.SendPropertyChanged("puntuacion");
					this.OnpuntuacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_ca", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_ca
		{
			get
			{
				return this._fecha_ca;
			}
			set
			{
				if ((this._fecha_ca != value))
				{
					this.Onfecha_caChanging(value);
					this.SendPropertyChanging();
					this._fecha_ca = value;
					this.SendPropertyChanged("fecha_ca");
					this.Onfecha_caChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servicioId", DbType="Int")]
		public System.Nullable<int> servicioId
		{
			get
			{
				return this._servicioId;
			}
			set
			{
				if ((this._servicioId != value))
				{
					if (this._Servicios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnservicioIdChanging(value);
					this.SendPropertyChanging();
					this._servicioId = value;
					this.SendPropertyChanged("servicioId");
					this.OnservicioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Servicios_Calificaciones", Storage="_Servicios", ThisKey="servicioId", OtherKey="Idservicio", IsForeignKey=true)]
		public Servicios Servicios
		{
			get
			{
				return this._Servicios.Entity;
			}
			set
			{
				Servicios previousValue = this._Servicios.Entity;
				if (((previousValue != value) 
							|| (this._Servicios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Servicios.Entity = null;
						previousValue.Calificaciones.Remove(this);
					}
					this._Servicios.Entity = value;
					if ((value != null))
					{
						value.Calificaciones.Add(this);
						this._servicioId = value.Idservicio;
					}
					else
					{
						this._servicioId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Servicios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Localidades")]
	public partial class Localidades : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idLocalidad;
		
		private string _nombre;
		
		private EntitySet<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidLocalidadChanging(int value);
    partial void OnidLocalidadChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public Localidades()
		{
			this._Usuarios = new EntitySet<Usuarios>(new Action<Usuarios>(this.attach_Usuarios), new Action<Usuarios>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLocalidad", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idLocalidad
		{
			get
			{
				return this._idLocalidad;
			}
			set
			{
				if ((this._idLocalidad != value))
				{
					this.OnidLocalidadChanging(value);
					this.SendPropertyChanging();
					this._idLocalidad = value;
					this.SendPropertyChanged("idLocalidad");
					this.OnidLocalidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Localidades_Usuarios", Storage="_Usuarios", ThisKey="idLocalidad", OtherKey="localidad")]
		public EntitySet<Usuarios> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Localidades = this;
		}
		
		private void detach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Localidades = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mascotas")]
	public partial class Mascotas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Idmascota;
		
		private string _tamaño;
		
		private string _edad;
		
		private System.Nullable<int> _raza;
		
		private string _nombre_ma;
		
		private System.Nullable<int> _Idusuario;
		
		private EntityRef<Razas> _Razas;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdmascotaChanging(int value);
    partial void OnIdmascotaChanged();
    partial void OntamañoChanging(string value);
    partial void OntamañoChanged();
    partial void OnedadChanging(string value);
    partial void OnedadChanged();
    partial void OnrazaChanging(System.Nullable<int> value);
    partial void OnrazaChanged();
    partial void Onnombre_maChanging(string value);
    partial void Onnombre_maChanged();
    partial void OnIdusuarioChanging(System.Nullable<int> value);
    partial void OnIdusuarioChanged();
    #endregion
		
		public Mascotas()
		{
			this._Razas = default(EntityRef<Razas>);
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idmascota", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Idmascota
		{
			get
			{
				return this._Idmascota;
			}
			set
			{
				if ((this._Idmascota != value))
				{
					this.OnIdmascotaChanging(value);
					this.SendPropertyChanging();
					this._Idmascota = value;
					this.SendPropertyChanged("Idmascota");
					this.OnIdmascotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tamaño", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tamaño
		{
			get
			{
				return this._tamaño;
			}
			set
			{
				if ((this._tamaño != value))
				{
					this.OntamañoChanging(value);
					this.SendPropertyChanging();
					this._tamaño = value;
					this.SendPropertyChanged("tamaño");
					this.OntamañoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string edad
		{
			get
			{
				return this._edad;
			}
			set
			{
				if ((this._edad != value))
				{
					this.OnedadChanging(value);
					this.SendPropertyChanging();
					this._edad = value;
					this.SendPropertyChanged("edad");
					this.OnedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raza", DbType="Int")]
		public System.Nullable<int> raza
		{
			get
			{
				return this._raza;
			}
			set
			{
				if ((this._raza != value))
				{
					if (this._Razas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrazaChanging(value);
					this.SendPropertyChanging();
					this._raza = value;
					this.SendPropertyChanged("raza");
					this.OnrazaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_ma", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_ma
		{
			get
			{
				return this._nombre_ma;
			}
			set
			{
				if ((this._nombre_ma != value))
				{
					this.Onnombre_maChanging(value);
					this.SendPropertyChanging();
					this._nombre_ma = value;
					this.SendPropertyChanged("nombre_ma");
					this.Onnombre_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idusuario", DbType="Int")]
		public System.Nullable<int> Idusuario
		{
			get
			{
				return this._Idusuario;
			}
			set
			{
				if ((this._Idusuario != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdusuarioChanging(value);
					this.SendPropertyChanging();
					this._Idusuario = value;
					this.SendPropertyChanged("Idusuario");
					this.OnIdusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Razas_Mascotas", Storage="_Razas", ThisKey="raza", OtherKey="idRaza", IsForeignKey=true)]
		public Razas Razas
		{
			get
			{
				return this._Razas.Entity;
			}
			set
			{
				Razas previousValue = this._Razas.Entity;
				if (((previousValue != value) 
							|| (this._Razas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Razas.Entity = null;
						previousValue.Mascotas.Remove(this);
					}
					this._Razas.Entity = value;
					if ((value != null))
					{
						value.Mascotas.Add(this);
						this._raza = value.idRaza;
					}
					else
					{
						this._raza = default(Nullable<int>);
					}
					this.SendPropertyChanged("Razas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Mascotas", Storage="_Usuarios", ThisKey="Idusuario", OtherKey="Idusuario", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Mascotas.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Mascotas.Add(this);
						this._Idusuario = value.Idusuario;
					}
					else
					{
						this._Idusuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Paseadores")]
	public partial class Paseadores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Idpaseador;
		
		private string _disponibilidad;
		
		private string _experiencia;
		
		private System.Nullable<double> _calificacion_prom;
		
		private string _especialidad;
		
		private System.Nullable<int> _pa_idusu;
		
		private System.Nullable<double> _precio;
		
		private string _estado;
		
		private EntitySet<PQR> _PQR;
		
		private EntitySet<Servicios> _Servicios;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdpaseadorChanging(int value);
    partial void OnIdpaseadorChanged();
    partial void OndisponibilidadChanging(string value);
    partial void OndisponibilidadChanged();
    partial void OnexperienciaChanging(string value);
    partial void OnexperienciaChanged();
    partial void Oncalificacion_promChanging(System.Nullable<double> value);
    partial void Oncalificacion_promChanged();
    partial void OnespecialidadChanging(string value);
    partial void OnespecialidadChanged();
    partial void Onpa_idusuChanging(System.Nullable<int> value);
    partial void Onpa_idusuChanged();
    partial void OnprecioChanging(System.Nullable<double> value);
    partial void OnprecioChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public Paseadores()
		{
			this._PQR = new EntitySet<PQR>(new Action<PQR>(this.attach_PQR), new Action<PQR>(this.detach_PQR));
			this._Servicios = new EntitySet<Servicios>(new Action<Servicios>(this.attach_Servicios), new Action<Servicios>(this.detach_Servicios));
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idpaseador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Idpaseador
		{
			get
			{
				return this._Idpaseador;
			}
			set
			{
				if ((this._Idpaseador != value))
				{
					this.OnIdpaseadorChanging(value);
					this.SendPropertyChanging();
					this._Idpaseador = value;
					this.SendPropertyChanged("Idpaseador");
					this.OnIdpaseadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_disponibilidad", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string disponibilidad
		{
			get
			{
				return this._disponibilidad;
			}
			set
			{
				if ((this._disponibilidad != value))
				{
					this.OndisponibilidadChanging(value);
					this.SendPropertyChanging();
					this._disponibilidad = value;
					this.SendPropertyChanged("disponibilidad");
					this.OndisponibilidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_experiencia", DbType="VarChar(20)")]
		public string experiencia
		{
			get
			{
				return this._experiencia;
			}
			set
			{
				if ((this._experiencia != value))
				{
					this.OnexperienciaChanging(value);
					this.SendPropertyChanging();
					this._experiencia = value;
					this.SendPropertyChanged("experiencia");
					this.OnexperienciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calificacion_prom", DbType="Float")]
		public System.Nullable<double> calificacion_prom
		{
			get
			{
				return this._calificacion_prom;
			}
			set
			{
				if ((this._calificacion_prom != value))
				{
					this.Oncalificacion_promChanging(value);
					this.SendPropertyChanging();
					this._calificacion_prom = value;
					this.SendPropertyChanged("calificacion_prom");
					this.Oncalificacion_promChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_especialidad", DbType="VarChar(50)")]
		public string especialidad
		{
			get
			{
				return this._especialidad;
			}
			set
			{
				if ((this._especialidad != value))
				{
					this.OnespecialidadChanging(value);
					this.SendPropertyChanging();
					this._especialidad = value;
					this.SendPropertyChanged("especialidad");
					this.OnespecialidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pa_idusu", DbType="Int")]
		public System.Nullable<int> pa_idusu
		{
			get
			{
				return this._pa_idusu;
			}
			set
			{
				if ((this._pa_idusu != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpa_idusuChanging(value);
					this.SendPropertyChanging();
					this._pa_idusu = value;
					this.SendPropertyChanged("pa_idusu");
					this.Onpa_idusuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Float")]
		public System.Nullable<double> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(10)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paseadores_PQR", Storage="_PQR", ThisKey="Idpaseador", OtherKey="idpas")]
		public EntitySet<PQR> PQR
		{
			get
			{
				return this._PQR;
			}
			set
			{
				this._PQR.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paseadores_Servicios", Storage="_Servicios", ThisKey="Idpaseador", OtherKey="pa_serv")]
		public EntitySet<Servicios> Servicios
		{
			get
			{
				return this._Servicios;
			}
			set
			{
				this._Servicios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Paseadores", Storage="_Usuarios", ThisKey="pa_idusu", OtherKey="Idusuario", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Paseadores.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Paseadores.Add(this);
						this._pa_idusu = value.Idusuario;
					}
					else
					{
						this._pa_idusu = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PQR(PQR entity)
		{
			this.SendPropertyChanging();
			entity.Paseadores = this;
		}
		
		private void detach_PQR(PQR entity)
		{
			this.SendPropertyChanging();
			entity.Paseadores = null;
		}
		
		private void attach_Servicios(Servicios entity)
		{
			this.SendPropertyChanging();
			entity.Paseadores = this;
		}
		
		private void detach_Servicios(Servicios entity)
		{
			this.SendPropertyChanging();
			entity.Paseadores = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PQR")]
	public partial class PQR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPQR;
		
		private System.DateTime _fecha_PQR;
		
		private string _comentario;
		
		private System.Nullable<int> _idusu;
		
		private System.Nullable<int> _idpas;
		
		private EntityRef<Paseadores> _Paseadores;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPQRChanging(int value);
    partial void OnIdPQRChanged();
    partial void Onfecha_PQRChanging(System.DateTime value);
    partial void Onfecha_PQRChanged();
    partial void OncomentarioChanging(string value);
    partial void OncomentarioChanged();
    partial void OnidusuChanging(System.Nullable<int> value);
    partial void OnidusuChanged();
    partial void OnidpasChanging(System.Nullable<int> value);
    partial void OnidpasChanged();
    #endregion
		
		public PQR()
		{
			this._Paseadores = default(EntityRef<Paseadores>);
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPQR", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdPQR
		{
			get
			{
				return this._IdPQR;
			}
			set
			{
				if ((this._IdPQR != value))
				{
					this.OnIdPQRChanging(value);
					this.SendPropertyChanging();
					this._IdPQR = value;
					this.SendPropertyChanged("IdPQR");
					this.OnIdPQRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_PQR", DbType="Date NOT NULL")]
		public System.DateTime fecha_PQR
		{
			get
			{
				return this._fecha_PQR;
			}
			set
			{
				if ((this._fecha_PQR != value))
				{
					this.Onfecha_PQRChanging(value);
					this.SendPropertyChanging();
					this._fecha_PQR = value;
					this.SendPropertyChanged("fecha_PQR");
					this.Onfecha_PQRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comentario", DbType="VarChar(100)")]
		public string comentario
		{
			get
			{
				return this._comentario;
			}
			set
			{
				if ((this._comentario != value))
				{
					this.OncomentarioChanging(value);
					this.SendPropertyChanging();
					this._comentario = value;
					this.SendPropertyChanged("comentario");
					this.OncomentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idusu", DbType="Int")]
		public System.Nullable<int> idusu
		{
			get
			{
				return this._idusu;
			}
			set
			{
				if ((this._idusu != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidusuChanging(value);
					this.SendPropertyChanging();
					this._idusu = value;
					this.SendPropertyChanged("idusu");
					this.OnidusuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idpas", DbType="Int")]
		public System.Nullable<int> idpas
		{
			get
			{
				return this._idpas;
			}
			set
			{
				if ((this._idpas != value))
				{
					if (this._Paseadores.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidpasChanging(value);
					this.SendPropertyChanging();
					this._idpas = value;
					this.SendPropertyChanged("idpas");
					this.OnidpasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paseadores_PQR", Storage="_Paseadores", ThisKey="idpas", OtherKey="Idpaseador", IsForeignKey=true)]
		public Paseadores Paseadores
		{
			get
			{
				return this._Paseadores.Entity;
			}
			set
			{
				Paseadores previousValue = this._Paseadores.Entity;
				if (((previousValue != value) 
							|| (this._Paseadores.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Paseadores.Entity = null;
						previousValue.PQR.Remove(this);
					}
					this._Paseadores.Entity = value;
					if ((value != null))
					{
						value.PQR.Add(this);
						this._idpas = value.Idpaseador;
					}
					else
					{
						this._idpas = default(Nullable<int>);
					}
					this.SendPropertyChanged("Paseadores");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_PQR", Storage="_Usuarios", ThisKey="idusu", OtherKey="Idusuario", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.PQR.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.PQR.Add(this);
						this._idusu = value.Idusuario;
					}
					else
					{
						this._idusu = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Razas")]
	public partial class Razas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRaza;
		
		private string _nombre;
		
		private EntitySet<Mascotas> _Mascotas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRazaChanging(int value);
    partial void OnidRazaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public Razas()
		{
			this._Mascotas = new EntitySet<Mascotas>(new Action<Mascotas>(this.attach_Mascotas), new Action<Mascotas>(this.detach_Mascotas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRaza", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idRaza
		{
			get
			{
				return this._idRaza;
			}
			set
			{
				if ((this._idRaza != value))
				{
					this.OnidRazaChanging(value);
					this.SendPropertyChanging();
					this._idRaza = value;
					this.SendPropertyChanged("idRaza");
					this.OnidRazaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Razas_Mascotas", Storage="_Mascotas", ThisKey="idRaza", OtherKey="raza")]
		public EntitySet<Mascotas> Mascotas
		{
			get
			{
				return this._Mascotas;
			}
			set
			{
				this._Mascotas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Mascotas(Mascotas entity)
		{
			this.SendPropertyChanging();
			entity.Razas = this;
		}
		
		private void detach_Mascotas(Mascotas entity)
		{
			this.SendPropertyChanging();
			entity.Razas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roles")]
	public partial class Roles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idrol;
		
		private string _nombre;
		
		private EntitySet<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidrolChanging(int value);
    partial void OnidrolChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public Roles()
		{
			this._Usuarios = new EntitySet<Usuarios>(new Action<Usuarios>(this.attach_Usuarios), new Action<Usuarios>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idrol", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idrol
		{
			get
			{
				return this._idrol;
			}
			set
			{
				if ((this._idrol != value))
				{
					this.OnidrolChanging(value);
					this.SendPropertyChanging();
					this._idrol = value;
					this.SendPropertyChanged("idrol");
					this.OnidrolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(20)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Roles_Usuarios", Storage="_Usuarios", ThisKey="idrol", OtherKey="Usu_rol")]
		public EntitySet<Usuarios> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Roles = this;
		}
		
		private void detach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Roles = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Servicios")]
	public partial class Servicios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Idservicio;
		
		private System.DateTime _fecha_se;
		
		private string _estado_se;
		
		private string _detalles_se;
		
		private System.Nullable<int> _se_idusuario;
		
		private System.Nullable<int> _pa_serv;
		
		private EntitySet<Calificaciones> _Calificaciones;
		
		private EntityRef<Paseadores> _Paseadores;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdservicioChanging(int value);
    partial void OnIdservicioChanged();
    partial void Onfecha_seChanging(System.DateTime value);
    partial void Onfecha_seChanged();
    partial void Onestado_seChanging(string value);
    partial void Onestado_seChanged();
    partial void Ondetalles_seChanging(string value);
    partial void Ondetalles_seChanged();
    partial void Onse_idusuarioChanging(System.Nullable<int> value);
    partial void Onse_idusuarioChanged();
    partial void Onpa_servChanging(System.Nullable<int> value);
    partial void Onpa_servChanged();
    #endregion
		
		public Servicios()
		{
			this._Calificaciones = new EntitySet<Calificaciones>(new Action<Calificaciones>(this.attach_Calificaciones), new Action<Calificaciones>(this.detach_Calificaciones));
			this._Paseadores = default(EntityRef<Paseadores>);
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idservicio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Idservicio
		{
			get
			{
				return this._Idservicio;
			}
			set
			{
				if ((this._Idservicio != value))
				{
					this.OnIdservicioChanging(value);
					this.SendPropertyChanging();
					this._Idservicio = value;
					this.SendPropertyChanged("Idservicio");
					this.OnIdservicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_se", DbType="Date NOT NULL")]
		public System.DateTime fecha_se
		{
			get
			{
				return this._fecha_se;
			}
			set
			{
				if ((this._fecha_se != value))
				{
					this.Onfecha_seChanging(value);
					this.SendPropertyChanging();
					this._fecha_se = value;
					this.SendPropertyChanged("fecha_se");
					this.Onfecha_seChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_se", DbType="VarChar(20)")]
		public string estado_se
		{
			get
			{
				return this._estado_se;
			}
			set
			{
				if ((this._estado_se != value))
				{
					this.Onestado_seChanging(value);
					this.SendPropertyChanging();
					this._estado_se = value;
					this.SendPropertyChanged("estado_se");
					this.Onestado_seChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detalles_se", DbType="VarChar(50)")]
		public string detalles_se
		{
			get
			{
				return this._detalles_se;
			}
			set
			{
				if ((this._detalles_se != value))
				{
					this.Ondetalles_seChanging(value);
					this.SendPropertyChanging();
					this._detalles_se = value;
					this.SendPropertyChanged("detalles_se");
					this.Ondetalles_seChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_se_idusuario", DbType="Int")]
		public System.Nullable<int> se_idusuario
		{
			get
			{
				return this._se_idusuario;
			}
			set
			{
				if ((this._se_idusuario != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onse_idusuarioChanging(value);
					this.SendPropertyChanging();
					this._se_idusuario = value;
					this.SendPropertyChanged("se_idusuario");
					this.Onse_idusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pa_serv", DbType="Int")]
		public System.Nullable<int> pa_serv
		{
			get
			{
				return this._pa_serv;
			}
			set
			{
				if ((this._pa_serv != value))
				{
					if (this._Paseadores.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpa_servChanging(value);
					this.SendPropertyChanging();
					this._pa_serv = value;
					this.SendPropertyChanged("pa_serv");
					this.Onpa_servChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Servicios_Calificaciones", Storage="_Calificaciones", ThisKey="Idservicio", OtherKey="servicioId")]
		public EntitySet<Calificaciones> Calificaciones
		{
			get
			{
				return this._Calificaciones;
			}
			set
			{
				this._Calificaciones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paseadores_Servicios", Storage="_Paseadores", ThisKey="pa_serv", OtherKey="Idpaseador", IsForeignKey=true)]
		public Paseadores Paseadores
		{
			get
			{
				return this._Paseadores.Entity;
			}
			set
			{
				Paseadores previousValue = this._Paseadores.Entity;
				if (((previousValue != value) 
							|| (this._Paseadores.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Paseadores.Entity = null;
						previousValue.Servicios.Remove(this);
					}
					this._Paseadores.Entity = value;
					if ((value != null))
					{
						value.Servicios.Add(this);
						this._pa_serv = value.Idpaseador;
					}
					else
					{
						this._pa_serv = default(Nullable<int>);
					}
					this.SendPropertyChanged("Paseadores");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Servicios", Storage="_Usuarios", ThisKey="se_idusuario", OtherKey="Idusuario", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Servicios.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Servicios.Add(this);
						this._se_idusuario = value.Idusuario;
					}
					else
					{
						this._se_idusuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Calificaciones(Calificaciones entity)
		{
			this.SendPropertyChanging();
			entity.Servicios = this;
		}
		
		private void detach_Calificaciones(Calificaciones entity)
		{
			this.SendPropertyChanging();
			entity.Servicios = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Idusuario;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _correo;
		
		private int _documento;
		
		private string _tipo_doc;
		
		private System.Nullable<int> _localidad;
		
		private System.Nullable<long> _telefono;
		
		private string _contrasena;
		
		private System.Nullable<int> _Usu_rol;
		
		private System.Data.Linq.Binary _ImgPerfil;
		
		private EntitySet<Mascotas> _Mascotas;
		
		private EntitySet<Paseadores> _Paseadores;
		
		private EntitySet<PQR> _PQR;
		
		private EntitySet<Servicios> _Servicios;
		
		private EntityRef<Roles> _Roles;
		
		private EntityRef<Localidades> _Localidades;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdusuarioChanging(int value);
    partial void OnIdusuarioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OndocumentoChanging(int value);
    partial void OndocumentoChanged();
    partial void Ontipo_docChanging(string value);
    partial void Ontipo_docChanged();
    partial void OnlocalidadChanging(System.Nullable<int> value);
    partial void OnlocalidadChanged();
    partial void OntelefonoChanging(System.Nullable<long> value);
    partial void OntelefonoChanged();
    partial void OncontrasenaChanging(string value);
    partial void OncontrasenaChanged();
    partial void OnUsu_rolChanging(System.Nullable<int> value);
    partial void OnUsu_rolChanged();
    partial void OnImgPerfilChanging(System.Data.Linq.Binary value);
    partial void OnImgPerfilChanged();
    #endregion
		
		public Usuarios()
		{
			this._Mascotas = new EntitySet<Mascotas>(new Action<Mascotas>(this.attach_Mascotas), new Action<Mascotas>(this.detach_Mascotas));
			this._Paseadores = new EntitySet<Paseadores>(new Action<Paseadores>(this.attach_Paseadores), new Action<Paseadores>(this.detach_Paseadores));
			this._PQR = new EntitySet<PQR>(new Action<PQR>(this.attach_PQR), new Action<PQR>(this.detach_PQR));
			this._Servicios = new EntitySet<Servicios>(new Action<Servicios>(this.attach_Servicios), new Action<Servicios>(this.detach_Servicios));
			this._Roles = default(EntityRef<Roles>);
			this._Localidades = default(EntityRef<Localidades>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idusuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Idusuario
		{
			get
			{
				return this._Idusuario;
			}
			set
			{
				if ((this._Idusuario != value))
				{
					this.OnIdusuarioChanging(value);
					this.SendPropertyChanging();
					this._Idusuario = value;
					this.SendPropertyChanged("Idusuario");
					this.OnIdusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_documento", DbType="Int NOT NULL")]
		public int documento
		{
			get
			{
				return this._documento;
			}
			set
			{
				if ((this._documento != value))
				{
					this.OndocumentoChanging(value);
					this.SendPropertyChanging();
					this._documento = value;
					this.SendPropertyChanged("documento");
					this.OndocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_doc", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string tipo_doc
		{
			get
			{
				return this._tipo_doc;
			}
			set
			{
				if ((this._tipo_doc != value))
				{
					this.Ontipo_docChanging(value);
					this.SendPropertyChanging();
					this._tipo_doc = value;
					this.SendPropertyChanged("tipo_doc");
					this.Ontipo_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_localidad", DbType="Int")]
		public System.Nullable<int> localidad
		{
			get
			{
				return this._localidad;
			}
			set
			{
				if ((this._localidad != value))
				{
					if (this._Localidades.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnlocalidadChanging(value);
					this.SendPropertyChanging();
					this._localidad = value;
					this.SendPropertyChanged("localidad");
					this.OnlocalidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="BigInt")]
		public System.Nullable<long> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="VarChar(50)")]
		public string contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this.OncontrasenaChanging(value);
					this.SendPropertyChanging();
					this._contrasena = value;
					this.SendPropertyChanged("contrasena");
					this.OncontrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usu_rol", DbType="Int")]
		public System.Nullable<int> Usu_rol
		{
			get
			{
				return this._Usu_rol;
			}
			set
			{
				if ((this._Usu_rol != value))
				{
					if (this._Roles.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsu_rolChanging(value);
					this.SendPropertyChanging();
					this._Usu_rol = value;
					this.SendPropertyChanged("Usu_rol");
					this.OnUsu_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgPerfil", DbType="Image", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ImgPerfil
		{
			get
			{
				return this._ImgPerfil;
			}
			set
			{
				if ((this._ImgPerfil != value))
				{
					this.OnImgPerfilChanging(value);
					this.SendPropertyChanging();
					this._ImgPerfil = value;
					this.SendPropertyChanged("ImgPerfil");
					this.OnImgPerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Mascotas", Storage="_Mascotas", ThisKey="Idusuario", OtherKey="Idusuario")]
		public EntitySet<Mascotas> Mascotas
		{
			get
			{
				return this._Mascotas;
			}
			set
			{
				this._Mascotas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Paseadores", Storage="_Paseadores", ThisKey="Idusuario", OtherKey="pa_idusu")]
		public EntitySet<Paseadores> Paseadores
		{
			get
			{
				return this._Paseadores;
			}
			set
			{
				this._Paseadores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_PQR", Storage="_PQR", ThisKey="Idusuario", OtherKey="idusu")]
		public EntitySet<PQR> PQR
		{
			get
			{
				return this._PQR;
			}
			set
			{
				this._PQR.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Servicios", Storage="_Servicios", ThisKey="Idusuario", OtherKey="se_idusuario")]
		public EntitySet<Servicios> Servicios
		{
			get
			{
				return this._Servicios;
			}
			set
			{
				this._Servicios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Roles_Usuarios", Storage="_Roles", ThisKey="Usu_rol", OtherKey="idrol", IsForeignKey=true)]
		public Roles Roles
		{
			get
			{
				return this._Roles.Entity;
			}
			set
			{
				Roles previousValue = this._Roles.Entity;
				if (((previousValue != value) 
							|| (this._Roles.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Roles.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Roles.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._Usu_rol = value.idrol;
					}
					else
					{
						this._Usu_rol = default(Nullable<int>);
					}
					this.SendPropertyChanged("Roles");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Localidades_Usuarios", Storage="_Localidades", ThisKey="localidad", OtherKey="idLocalidad", IsForeignKey=true)]
		public Localidades Localidades
		{
			get
			{
				return this._Localidades.Entity;
			}
			set
			{
				Localidades previousValue = this._Localidades.Entity;
				if (((previousValue != value) 
							|| (this._Localidades.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Localidades.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Localidades.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._localidad = value.idLocalidad;
					}
					else
					{
						this._localidad = default(Nullable<int>);
					}
					this.SendPropertyChanged("Localidades");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Mascotas(Mascotas entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_Mascotas(Mascotas entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
		
		private void attach_Paseadores(Paseadores entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_Paseadores(Paseadores entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
		
		private void attach_PQR(PQR entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_PQR(PQR entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
		
		private void attach_Servicios(Servicios entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_Servicios(Servicios entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
	}
	
	public partial class OrganizarusuarioResult
	{
		
		private int _Idusuario;
		
		private string _nombre;
		
		private string _Apellido;
		
		private System.Nullable<long> _telefono;
		
		private string _correo;
		
		private string _nombre1;
		
		public OrganizarusuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idusuario", DbType="Int NOT NULL")]
		public int Idusuario
		{
			get
			{
				return this._Idusuario;
			}
			set
			{
				if ((this._Idusuario != value))
				{
					this._Idusuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="BigInt")]
		public System.Nullable<long> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre1
		{
			get
			{
				return this._nombre1;
			}
			set
			{
				if ((this._nombre1 != value))
				{
					this._nombre1 = value;
				}
			}
		}
	}
	
	public partial class buscarResult
	{
		
		private int _Idusuario;
		
		public buscarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idusuario", DbType="Int NOT NULL")]
		public int Idusuario
		{
			get
			{
				return this._Idusuario;
			}
			set
			{
				if ((this._Idusuario != value))
				{
					this._Idusuario = value;
				}
			}
		}
	}
	
	public partial class buscarpaseadorNResult
	{
		
		private int _Idpaseador;
		
		private string _nombre;
		
		private string _Apellido;
		
		private System.Nullable<long> _telefono;
		
		private string _correo;
		
		private System.Nullable<int> _localidad;
		
		private System.Nullable<double> _precio;
		
		public buscarpaseadorNResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idpaseador", DbType="Int NOT NULL")]
		public int Idpaseador
		{
			get
			{
				return this._Idpaseador;
			}
			set
			{
				if ((this._Idpaseador != value))
				{
					this._Idpaseador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="BigInt")]
		public System.Nullable<long> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_localidad", DbType="Int")]
		public System.Nullable<int> localidad
		{
			get
			{
				return this._localidad;
			}
			set
			{
				if ((this._localidad != value))
				{
					this._localidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Float")]
		public System.Nullable<double> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this._precio = value;
				}
			}
		}
	}
	
	public partial class ConsultarpaseadorResult
	{
		
		private int _Idpaseador;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<long> _telefono;
		
		private string _correo;
		
		private System.Nullable<int> _localidad;
		
		private string _tipo_doc;
		
		private int _documento;
		
		public ConsultarpaseadorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idpaseador", DbType="Int NOT NULL")]
		public int Idpaseador
		{
			get
			{
				return this._Idpaseador;
			}
			set
			{
				if ((this._Idpaseador != value))
				{
					this._Idpaseador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="BigInt")]
		public System.Nullable<long> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_localidad", DbType="Int")]
		public System.Nullable<int> localidad
		{
			get
			{
				return this._localidad;
			}
			set
			{
				if ((this._localidad != value))
				{
					this._localidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_doc", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string tipo_doc
		{
			get
			{
				return this._tipo_doc;
			}
			set
			{
				if ((this._tipo_doc != value))
				{
					this._tipo_doc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_documento", DbType="Int NOT NULL")]
		public int documento
		{
			get
			{
				return this._documento;
			}
			set
			{
				if ((this._documento != value))
				{
					this._documento = value;
				}
			}
		}
	}
	
	public partial class OrganizarPaseadorResult
	{
		
		private int _Idpaseador;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<long> _telefono;
		
		private string _estado;
		
		private string _correo;
		
		private string _nombre1;
		
		private System.Nullable<double> _precio;
		
		public OrganizarPaseadorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idpaseador", DbType="Int NOT NULL")]
		public int Idpaseador
		{
			get
			{
				return this._Idpaseador;
			}
			set
			{
				if ((this._Idpaseador != value))
				{
					this._Idpaseador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="BigInt")]
		public System.Nullable<long> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(10)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre1
		{
			get
			{
				return this._nombre1;
			}
			set
			{
				if ((this._nombre1 != value))
				{
					this._nombre1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Float")]
		public System.Nullable<double> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this._precio = value;
				}
			}
		}
	}
	
	public partial class mostrarimagenResult
	{
		
		private System.Data.Linq.Binary _ImgPerfil;
		
		public mostrarimagenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgPerfil", DbType="Image", CanBeNull=true)]
		public System.Data.Linq.Binary ImgPerfil
		{
			get
			{
				return this._ImgPerfil;
			}
			set
			{
				if ((this._ImgPerfil != value))
				{
					this._ImgPerfil = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
